import education.data, education.pupil, education.teacher
lesson=education.data.Data('class', 'object', 'inheritance', 'polymorphism', 'encapsulation')
mariaIvanovna=education.teacher.Teacher()
ivan=education.pupil.Pupil()
vera=education.pupil.Pupil()
mariaIvanovna.teach(lesson[3],ivan,vera)
mariaIvanovna.teach(lesson[0],ivan)
print(ivan.knowelege)
print(vera.knowelege)
vera.take(lesson[4])
print(vera.knowelege)
vera.take(lesson[3])
vera.take(lesson[2])
vera.take(lesson[0])
print(vera.knowelege)
vera.__del__()
print(vera.knowelege)